### ISSUE TITLE
Evaluation server does not working

### ISSUE THREAD

**Issue by Y111555** [miccunifi/CIRCO#3]
Hello, 
thank you for the excellent work! It seems that the evaluation server is currently not functioning. Could you please check on this? 
Much appreciated!

**Comment by ABaldrati** [comment]
Hi @Y111555 

Thanks for your interest in our work!

You are right, our evaluation server is currently experiencing connection issues, which are beyond our control. Unfortunately, due to the laboratory being closed for the summer holidays, we are unable to resolve these issues immediately. 

Given the urgency of the AAAI deadline on August 15th, we have implemented a temporary solution. If you have an urgent need to evaluate your predictions, you may submit your `.json` file to the email address: **micc.noreply@gmail.com**. Please note that this option is available **only for urgent cases** and is limited to a maximum of **three predictions per day**.

We will ensure that the evaluation metrics are sent to you at least once per day until August 19th (the submission deadline for supplementary materials). The final guaranteed evaluation will be conducted at **4:00 PM AoT on August 15th** (and similarly on August 19th for supplementary materials).

We sincerely apologize for the inconvenience and are working to restore the server as soon as possible.

**Comment by ABaldrati** [comment]
Hi @Y111555 

I am happy to announce that the evaluation server is working again!
We are no longer accepting submissions by mail.

**Comment by Y111555** [comment]
OK, Thank you for your efforts.
